### ISSUE TITLE
Change to env variable

### ISSUE THREAD

**Issue by dca123** [dataXdevelopment/SEELE#1]
Hard links to path directories & API keys should be referred to by an ENV variable. Or do we pass it as a string ? 

We could have a function instance.setup to init the location. 

The driver code can use an ENV variable to use it.

https://github.com/dataXdevelopment/SEELE/blob/b9bd2f719e7e5c6a25f28c446a1d1d6aa4a46a37/Scrapers/meta_factored.py#L36

**Comment by dayanadithyan** [comment]
Addressed 16/10/21.
